### ISSUE TITLE
Add missing maturity icons for "Retired" and "Living Standard"

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#111]
The WHATWG logo seems good for the "Living Standard" maturity level.

Not sure what to use for "Retired" specs for now. A circle with an orange stroke perhaps.

**Comment by tidoust** [comment]
I added new icons next to existing ones:
- [Group Note](https://www.w3.org/2013/09/wpd-rectrack-icons/note.svg): same icon as for a Rec to mark the fact that the spec is usually stable once published as a Note, but text says "Note"
- [Retired](https://www.w3.org/2013/09/wpd-rectrack-icons/retired.svg): contains a cross to alert that the spec should no longer be considered.
- [Living Standard](https://www.w3.org/2013/09/wpd-rectrack-icons/ls.svg): same icon as for a Rec with multiple "release" points to mark the fact that the document is continuously being updated. I did not use the WHATWG logo in the end to keep a visual consistency across icons.

With these new icons, I believe that this issue can be closed once PR #148 has been merged.

**Comment by xfq** [comment]
Closing since #148 has been merged. Thank you!

**Comment by xfq** [comment]
The phrase "Living Standard" looks so small on my browser... Should we use "LS" instead? (It's also more consistent with other maturity levels.)

**Comment by tidoust** [comment]
I switched to "LS". That said, the text on all icons remains rather small, so I created another issue to improve readability.
