### ISSUE TITLE
Add templating mechanism for translation strings

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#114]
From #110, translations do not support templating for now (i.e. there is no way to have a string such as ``The group %1 developed the %2 specification`). It most likely should. We might need to support singular/plural forms as well.

I don't know if we can live with a basic system or if that means we need to switch to using a Gettext style library such as [Jed](https://messageformat.github.io/Jed/).

**Comment by xfq** [comment]
Fixed in #119.
