### ISSUE TITLE
Create an "about" page

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#122]
The roadmap documents should link to some kind of about page that describes:
- the generic purpose of the document;
- the intended audience;
- the intended level of details;
- the group responsible for the maintenance of the document, if any, individuals who maintain the document otherwise;
- the current status of the document (stable, draft, complete, sketchy, whether identified gaps represent the consensus of a group or do not convey any sense of priority for now);
- how to provide comments
- whether snapshots of the document are being published somewhere, and the frequency of these publications.
- etc.

Some of this information seems common to all roadmaps, so the easiest way is probably to develop an about template page that can be completed in individual roadmaps.

**Comment by xfq** [comment]
Fixed in #221.
