### ISSUE TITLE
Ambient humidity events seems deprecated

### ISSUE THREAD

**Issue by kenchris** [w3c/web-roadmaps#159]
https://dvcs.w3.org/hg/dap/raw-file/tip/humidity/Overview.html

I also had a newer proposal based on generic sensors, but I don't think I migrated to from our internal servers, so it might have been lost. It should be very easy to create one if there is interest though.

These are a few additional ones

https://github.com/kenchris/thermometer
https://github.com/kenchris/barometer

**Comment by xfq** [comment]
Fixed by #187.
