### ISSUE TITLE
Mobile roadmap should refer to CSS Grid

### ISSUE THREAD

**Issue by js-choi** [w3c/web-roadmaps#169]
[Roadmap of Web Applications on Mobile: Graphics & Layout](https://w3c.github.io/web-roadmaps/mobile/graphics.html) discusses CSS Flexible Layout (flexbox) but not CSS Grid Layout. Grid should be added to the page too.

**Comment by xfq** [comment]
I had hesitated to mention Grid Layout, because it's optimized for 2-dimensional layouts, which isn't very common on mobile devices, AFAIK. But I guess Grid can also be used for responsive web design (for layouts that can be adapted for both larger screens and smaller ones), so perhaps it's OK to include Grid.

@tidoust, WDYT?

**Comment by js-choi** [comment]
Even though CSS Grid is bidimensional, it still is useful in any application or document that requires top-down / outside-in sizing of a predefined layout with predefined dimensions. This top-down perspective remains true for 1×many or many×1 grids, but it stands in contrast to Flexbox. Flexbox flows and sizes layout, bottom-up / inside-out, using each content item’s flex properties. Both are useful in mobile layouts. [Rachel Andrews of the CSSWG discussed Grid versus Flexbox in 2016][andrews]; I found the article’s final section illuminating.

Many×many layouts are also common enough on mobile devices. Tablets are mobile devices, for one, and they are large. But [even phones find use for collection views requiring alignment in both dimensions](http://i.stack.imgur.com/4dCZC.png).

Thanks for considering. This is one of the most useful documents I’ve yet seen from W3C; it puts so many disparate specifications in their contexts (both aspirational and practical).

[andrews]: https://www.rachelandrew.co.uk/archives/2016/03/30/should-i-use-grid-or-flexbox/

**Comment by xfq** [comment]
Fair enough, and thanks for the great comments! I'll add CSS Grid to the mobile roadmap.
