### ISSUE TITLE
Add building-related docs

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#17]
Mention dependencies like python/make/lxml/jsonschema/html5validator, and document the build process.

Example: https://github.com/validator/validator/blob/master/CONTRIBUTING.md#want-to-build-test-and-run-the-code

**Comment by tidoust** [comment]
We can obviously always improve the doc, but the [build process](https://github.com/w3c/web-roadmaps#generate-content-locally) is now documented in the README. Dependencies are automatically installed by `npm`. The one thing we cannot really automate is the creation of a W3C API key, but that as well is explained in the README.

I'm closing this issue as a result. Let's create more specific issues if needed.
