### ISSUE TITLE
Support Python 3?

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#177]
Python 2 support [will end in 2020](https://www.python.org/dev/peps/pep-0373/#maintenance-releases):

> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. The current plan is to support it for at least 10 years from the initial 2.7 release. This means there will be bugfix releases until 2020.

We probably want to support Python 3.x before the end of Python 2.7. Another option is switching to a language we're more familiar with (such as JavaScript).

**Comment by tidoust** [comment]
No Python anymore, as PR #206 switched scripts to JavaScript. I'm closing this issue as a result.
