### ISSUE TITLE
Update part on WOFF

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#185]
The [graphics](https://w3c.github.io/web-roadmaps/mobile/graphics.html) page mentions qualifies WOFF 2.0 as _upcoming_. WOFF 2.0 has been published as a Recommendation and is supported across browsers, so the part needs to be updated.

We can probably drop the link to WOFF 1.0 altogether and only talk about WOFF 2.0.

**Comment by xfq** [comment]
Fixed in #194. Thanks!
