### ISSUE TITLE
Update appcache text and move to discontinued features

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#191]
As noted in PR #189, appcache was entirely removed from HTML 5.2 (although it still is in [HTML LS](https://html.spec.whatwg.org/multipage/offline.html#offline)). The [lifecycle](https://w3c.github.io/web-roadmaps/mobile/lifecycle.html) text merely talks about HTML 5.1 and should be updated to note that the feature has been dropped entirely in HTML 5.2.

Also, although the feature is indeed well-deployed, we should probably move it to the discontinued features section to make it clear that developers are no longer encouraged to use it.

**Comment by xfq** [comment]
Fixed in #193. Thank you!
