### ISSUE TITLE
mdn-browser-compat-data as another data source?

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#197]
https://github.com/mdn/browser-compat-data

IIUC it has more feature coverage than caniuse, and the data is on a more granular level (but not to the point of wpt.fyi).

/cc @dontcallmedom

**Comment by tidoust** [comment]
The MDN Browser Compatibility Data can now be referenced in data files through the `mdn` property (see README for details). Closing the issue as a result. I created #271 to track updates to data files.
