### ISSUE TITLE
Improve "group" logic for specs retrieved from Specref

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#208]
See [discussion in PR #207](https://github.com/w3c/web-roadmaps/pull/207#discussion_r180656858)

Specref can return:
1. a `deliveredBy` property with the list of groups that delivered the spec. But group labels are missing.
2. a `publisher` property that contains the name of the publisher... which is sometimes the name of the group itself, i.e. for WHATWG (e.g. [info on XHR](https://api.specref.org/reverse-lookup?urls=https://xhr.spec.whatwg.org/)) or for W3C CGs (e.g. [info on Web Bluetooth](https://api.specref.org/reverse-lookup?urls=https://webbluetoothcg.github.io/web-bluetooth/))

Code should probably:
1. mix both properties when they exist to associate the publisher's name with the group's URL.
2. use the `publisher` property otherwise to create a "working group" (a short list of well-known URLs for IETF and WHATWG should give us a URL)
3. add a `publisher` property to `tr.json`, as it could be a useful information

**Comment by xfq** [comment]
Fixed by #209.
