### ISSUE TITLE
extract-spec-data.py cannot find some WGs

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#23]
[data/contacts-sys.json](https://github.com/w3c/media-web-roadmap/blob/fd673d76bed425968805a7d1689d7b319356b100/data/contacts-sys.json) causes the following error:

```
No group with home page http://www.w3.org/2012/sysapps/ found in public-groups.rdf nor closed-groups.rdf
```

Possible reason: The System Applications Working Group was closed, and no further work on the Contacts Manager API is expected.

-----

[data/indexeddb.json](https://github.com/w3c/media-web-roadmap/blob/fd673d76bed425968805a7d1689d7b319356b100/data/indexeddb.json), [data/websql.json](https://github.com/w3c/media-web-roadmap/blob/fd673d76bed425968805a7d1689d7b319356b100/data/websql.json), and [data/webstorage.json](https://github.com/w3c/media-web-roadmap/blob/fd673d76bed425968805a7d1689d7b319356b100/data/webstorage.json) cause the following error:

```
No group with home page http://www.w3.org/2008/webapps/ found in public-groups.rdf nor closed-groups.rdf
```

Possible reasons: WebApps is WebPlat now; Web SQL was abandoned.

-----

Is there anything I can do to fix these errors?

/cc @dontcallmedom

**Comment by tidoust** [comment]
I completed the list of closed groups in [`closed-groups.rdf`](http://www.w3.org/2000/04/mem-news/closed-groups.rdf), used by the Python code for groups it cannot find in the list of active groups. The generation no longer reports any error.

Closing this as a result.

**Comment by xfq** [comment]
Cool. The Travis CI build log will be shorter after this fix.
