### ISSUE TITLE
Include main roadmap title in individual pages

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#238]
The title of the multi-page roadmap does not appear in individual pages. It provides useful context. For instance, if you're looking at "Graphics and Layout", it's useful to know right away that the page is part of the mobile roadmap, and thus that technologies listed in that page have a mobile twist to them.

Practically, this could perhaps be done with a tagline below the page title, such as "part of the Roadmap of Web Applications on Mobile".

**Comment by xfq** [comment]
This might be good for SEO too.

(Which makes me think whether we should add `<meta name="description" content="...">` to the pages.)

**Comment by tidoust** [comment]
Issue #250 created to track the "meta" comment. Done otherwise.
