### ISSUE TITLE
"This Version" and "Editor's Draft" metadata are wrong in the Editor's Draft

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#244]
The links to "This Version" and "Editor's Draft" are incorrect in https://w3c.github.io/web-roadmaps/mobile/ :

```
This version
    https://w3c.github.io/web-roadmaps/home/travis/build/w3c/web-roadmaps/mobile/
Editor's Draft
    https://w3c.github.io/web-roadmaps/home/travis/build/w3c/web-roadmaps/mobile/
```

**Comment by tidoust** [comment]
Argh, indeed! I pushed a fix to the `master` branch. The fix assumes that the repo is cloned to a folder whose name is the name of the repo. That should be true most of the time, but that assumption may not hold if someone decides to clone the repo to a folder named differently. I don't really see how to avoid that and still be able to compute the right Editor's Draft URL from the GitHub repository URL.

**Comment by tidoust** [comment]
Ah, if you're nostalgic of the old name, setting the `edDraft` property in the `toc.json` file would do the trick! :-)
