### ISSUE TITLE
Add "gesture" in the list of gaps for "interactions"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/web-roadmaps#261]
cf https://www.w3.org/community/mwma/2018/05/22/call-for-participation-online-meeting-on-gesture-events-standard-in-web/

**Comment by xfq** [comment]
Related discussions: https://lists.w3.org/Archives/Public/public-wicg/2018May/0001.html

**Comment by xfq** [comment]
I think this can be in "Features not covered by ongoing work" of the User Interaction section.
