### ISSUE TITLE
Mention CSS Containment

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#276]
The [CSS Containment](https://www.w3.org/TR/css-contain-1/) spec defines the `contain` property, which indicates that the element’s subtree is independent of the rest of the page. This enables heavy optimizations by user agents when used well, in particular to skip over content that is off-screen knowing that it won't affect the rendering of the content that is on-screen.

That seems even more useful on "small" mobile screens.

**Comment by xfq** [comment]
This feature is similar to [CSS Will Change](https://www.w3.org/TR/css-will-change-1/), because both of them are about performance. Personally, I prefer mentioning it in the Performance and Tuning section, instead of the Graphics and Layout section. WDYT, @tidoust?
