### ISSUE TITLE
Mention Priority Hints

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#280]
The [Priority Hints](https://wicg.github.io/priority-hints/) spec describes a browser API enabling developers to signal the priority of each resource they need to download, giving more control than `preload`.

We should mention that spec  in Performance along with Preload.

**Comment by xfq** [comment]
In the "Features not covered by on-going work" section of Performance and Tuning, there's a "more fine-grained network prioritization".

Should we keep that section (given that Priority Hints has been added now)?
