### ISSUE TITLE
Mention Animation Worklet

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#281]
The [CSS Animation Worklet API](https://wicg.github.io/animation-worklet/) proposal "provides a method to create scripted animations that control a set of animation effects. The API is designed to make it possible for user agents to run such animations in their own dedicated thread to provide a degree of performance isolation from main thread".

**Comment by xfq** [comment]
This seems to be more about Performance and Tuning than Graphics and Layout. I'll add it later.

**Comment by tidoust** [comment]
I don't disagree... but then we talk about other related aspects of animations in "Graphics and Layouts". Another case where it might be worth adding the spec in both sections (which is what we did for `requestAnimationFrame`).

**Comment by tidoust** [comment]
Given that the intro text of the Graphics and Layout page now explicitly links to the Performance and Tuning page for such specs, there should no longer be any need to duplicate that spec in the Graphics and Layout page.
