### ISSUE TITLE
Mention Web Budget API

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#282]
The [Web Budget API](https://wicg.github.io/budget-api/) describes an API that can be used to retrieve the amount of budget an origin has available for resource consuming background operations, as well as the cost associated with doing such an operation.

The notion of "cost" typically includes being on battery power or under restricted network conditions.

**Comment by xfq** [comment]
Which section should it be mentioned? Maybe Application Lifecycle?

**Comment by tidoust** [comment]
I guess I was more thinking about "Performance and Tuning" initially, but putting it in "Application Lifecycle" seems a good idea! It could be mentioned in both sections if that seems useful.
