### ISSUE TITLE
TTWG deliverables need to be updated.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/web-roadmaps#283]
IMSC 1 is listed as "retired" and is superseded but has been replaced by the IMSC 1.0.1 Rec - this needs to be added.

Work is progressing towards:

- TTML2 (currently in CR2)
- IMSC 1.1 (profile of TTML2 backwards compatible with IMSC 1.0.1, currently in CR, about to be in CR2)
- TTML1 3rd Edition (currently in CR)

**Comment by tidoust** [comment]
@nigelmegitt See #305 for a pull request that updates the content as suggested. Would that be fine?

Would you have more text to suggest to present the different versions? For instance, I'm not entirely clear how to present TTML2 in relation to TTML1. Sure enough, that's a second version, but are there notable new features in TTML2 that might be worth pointing out in particular? It's fine if it's just "more better" (I see the change section in IMSC1.1 lists a number of new features compared to IMSC1.0.1 for instance), in which case the current text seems good enough.

**Comment by nigelmegitt** [comment]
@tidoust TTML2 adds a lot of additional features not present in TTML1. There are so many to mention that it's difficult - the TTML2 SoTD includes a change summary that lists them and there's also a section at https://w3c.github.io/ttml2/index.html#changes-from-ttml1-vocabulary that lists them. The system model is slightly extended to include better profile association and to include intermediate documents. The language support includes Japanese and other languages. There is a conditional processing model that could be used with media queries to make responsive presentations, for example. Audio renderings of timed text are supported. It's a big delta!

**Comment by tidoust** [comment]
OK, thanks for the explanation! My takeaway is that the text in the pull request that was merged is good enough for now. Closing this issue as a result.
