### ISSUE TITLE
Repository name 

### ISSUE THREAD

**Issue by chrisn** [w3c/web-roadmaps#32]
As this repo contains roadmaps for media, security, and now mobile features, the name "media-web-roadmap" might be confusing. Should we consider renaming, e.g.,  to "web-feature-roadmaps"?

We also discussed among the Media & Entertainment IG co-chairs using the term Overview rather than Roadmap as these pages don't currently contain timelines for each feature. WDYT?

**Comment by tidoust** [comment]
> As this repo contains roadmaps for media, security, and now mobile features, the name "media-web-roadmap" might be confusing. Should we consider renaming, e.g., to "web-feature-roadmaps"?

Right, I'm not making any change right now, but I expect to be discussing code organization next week internally. On top of renaming the repo, it might actually be worth splitting the repository into different repositories in the end:

- one repository for the code of the framework
- one repository for spec data
- one repository per actual roadmap

> We also discussed among the Media & Entertainment IG co-chairs using the term Overview rather than Roadmap as these pages don't currently contain timelines for each feature. WDYT?

I agree and implemented the change.

**Comment by tidoust** [comment]
We'll probably just stick to one repository for now, as long as there are just a handful roadmaps that make use of the tool.

It seems wise to change the name of the repository to a more generic name while things are still fresh, though. We'll leave a redirect from the old pages to the new ones.

Regarding naming options, suggestions include "web-feature-roadmaps", "web-roadmaps", "webroadmaps", perhaps even simply "roadmaps". Any strong feeling about any of them?

I would personally prefer "webroadmaps", both simple and expressive enough.

Cc @dontcallmedom

**Comment by dontcallmedom** [comment]
any of the options above work for me; I find "web-roadmaps" more readable, but have no strong feelings either way.

**Comment by tidoust** [comment]
@xfq seems to like the hyphen too, so I moved the repository to a repository named "web-roadmaps".

The [media-web-roadmap repository](https://github.com/w3c/media-web-roadmap) that only contains redirects to the new pages.
