### ISSUE TITLE
"retired-informative" icon 404

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#320]
In [js/generate-utils.js](https://github.com/w3c/web-roadmaps/blob/9015ba06bc4c3f5994fe83eaae335e4c922202b2/js/generate-utils.js#L526):

```javascript
  let iconSrc =
    'https://www.w3.org/2013/09/wpd-rectrack-icons/' +
    (spec.evergreen ? 'REF' : spec.status).toLowerCase() +
    (spec.informative ? '-informative' : '') +
    '.svg';
```

The DeviceOrientation Event Specification is "retired-informative", but https://www.w3.org/2013/09/wpd-rectrack-icons/ doesn't contain a corresponding SVG file.

**Comment by tidoust** [comment]
Created a new [retired-informative](https://www.w3.org/2013/09/wpd-rectrack-icons/retired-informative.svg) icon that uses the grey color.
