### ISSUE TITLE
Mention Background Fetch

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#323]
See https://github.com/WICG/background-fetch for more info.

**Comment by xfq** [comment]
It can be mentioned in `network.html` and/or `lifecycle.html`, next to Web Background Synchronization.

**Comment by xfq** [comment]
Chrome Platform Status: https://www.chromestatus.com/feature/5712608971718656

**Comment by tidoust** [comment]
Fixed by #352
