### ISSUE TITLE
Mention KV Storage

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#366]
* GitHub: https://github.com/WICG/kv-storage
* Chrome Platform Status: https://www.chromestatus.com/feature/6428344899862528

**Comment by xfq** [comment]
In the README of the spec repo:

> At TPAC 2018, the Web Platform Working Group and the IndexedDB specification editors agreed that after incubation in the WICG, KV storage should graduate to be part of the W3C IndexedDB specification.

Is it useful to mention that in the paragraph for IndexedDB?

**Comment by tidoust** [comment]
> Is it useful to mention that in the paragraph for IndexedDB?

I think I would actually mention it in the description of KV storage once we have it, with something along the lines of "Plan is for that spec to get merged in IndexedDB after incubation".
