### ISSUE TITLE
Move Hardware Based Secure Services to discontinued features?

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#388]
The [Hardware Based Secure Services](https://rawgit.com/w3c/websec/gh-pages/hbss.html) document hasn't been updated for more than two years. Should we move it to the [discontinued features](https://w3c.github.io/web-roadmaps/mobile/security.html#discontinued-features) section?

A friendly ping to @wseltzer, as she might know the current status better than me.

**Comment by wseltzer** [comment]
it's not under active development, so +1 to marking discontinued
