### ISSUE TITLE
Web Audio not "experimental" in Chrome

### ISSUE THREAD

**Issue by svgeesus** [w3c/web-roadmaps#427]
[Media Rendering Roadmap](https://w3c.github.io/web-roadmaps/media/rendering.html) lists Web Audio API as "experimental" in Chrome. 

Chrome is actually the leading implementation in terms of spec compliance.

[Prefixed Web Audio was enabled by default in Chrome 14; the unprefixed version in Chrome 34](https://www.chromestatus.com/feature/6261718720184320)

**Comment by tidoust** [comment]
That incorrect info actually comes from the corresponding entry in JSON file exposed by Chromestatus. I filed an issue over there: https://github.com/GoogleChrome/chromium-dashboard/issues/685
