### ISSUE TITLE
Mention prefers-color-scheme

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#448]
With the `prefers-color-scheme` media feature, users can choose to adopt a dark appearance instead of a light appearance of the webpage.

* Spec: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme
* Can I use: https://caniuse.com/#search=prefers-color-scheme
* Chrome Platform Status: https://www.chromestatus.com/feature/5109758977638400

**Comment by xfq** [comment]
Where should we add it? Graphics and Layout?

**Comment by tidoust** [comment]
I would add it to [Device Adaptation](https://w3c.github.io/web-roadmaps/mobile/adaptation.html) since this is where CSS Media Queries appears. Granted, this is more about "user" adaptation, but the "adaptation" part is what matters here.
