### ISSUE TITLE
Mention Color on the Web CG report

### ISSUE THREAD

**Issue by chrisn** [w3c/web-roadmaps#459]
The Color on the Web CG is working on a gap analysis report for High Dynamic Range and Wide Gamut Color on the Web: https://w3c.github.io/ColorWeb-CG/. For completeness, it would be good to add this to the [Rendering](https://w3c.github.io/web-roadmaps/media/rendering.html) section of the Overview of Media Technologies for the Web.

**Comment by xfq** [comment]
Yeah, it can be added to https://w3c.github.io/web-roadmaps/mobile/media.html as well.
