### ISSUE TITLE
Mention Mini Apps incubations

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#487]
Mini apps environments mostly target smartphones. It would seem useful to reference the work of the MiniApps CG and ongoing discussions on convergence with Web apps in Application Lifecycle.

See [MiniApps specifications](https://github.com/w3c/miniapp/tree/gh-pages/specs#miniapp-specifications)

**Comment by xfq** [comment]
Given that the MiniApp vendors have not yet implemented the MiniApp specs (in an interoperable way), I think it would be better to have a general introduction for now, rather than introduce each proposal in the CG one by one. WDYT?

**Comment by tidoust** [comment]
I agree and tried to do just that in #500.
