### ISSUE TITLE
Mention User Idle Detection

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#489]
- See explainer: https://github.com/WICG/idle-detection#user-idle-detection
- Chrome status: https://www.chromestatus.com/features/4590256452009984
- Mention in: Application lifecycle. Possibly also in Performance and Tuning (`requestIdleCallback` is mentioned in both)

**Comment by xfq** [comment]
I think it is enough to mention it in Application lifecycle, because this has very little relationship with performance. Unlike `requestIdleCallback`, this is not about scheduling work, and is more about notifications.

**Comment by tidoust** [comment]
Good point, I'll stick to Application Lifecycle!
