### ISSUE TITLE
Maps and coordinate systems in HTML

### ISSUE THREAD

**Issue by prushforth** [w3c/web-roadmaps#513]
I was wondering if I'd missed it.  We've been working on this for some time now, perhaps it's time to put our community group's objectives on your road map?  https://maps4html.org  Any help raising the profile and participation in this initiative would be appreciated.

Thanks

**Comment by tidoust** [comment]
I take it that you mean that MapML should be added to the mobile version of the roadmap. That seems fine and it's certainly relevant (mobile devices are heavily used for directions!). Interestingly, I don't exactly know where to put it for the time being, as it does not quite fit in any of the existing pages... Thoughts?

**Comment by prushforth** [comment]
Yes, apologies I forgot that there are many roadmaps.  Weird that it doesn't categorize well, but on the other hand seems to fit into every category in some way.  Rather than rock the boat, I think I'll just close this until when /if it becomes more obvious where to put it. Thanks and sorry for bothering you.
