### ISSUE TITLE
Support linking to more than one ID on status platforms

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#59]
From time to time, the granularity of a feature in our roadmap will be coarser than the granularity for that same feature in status platforms. In such case, it would be useful to be able to link to different IDs in the JSON file that describes the feature.

The code that computes the actual implementation status should check the IDs and only consider that a browser supports the feature when it supports all of the sub-features.

An example is the Storage spec which exists as [5630353511284736](https://www.chromestatus.com/feature/5630353511284736), [4931497563783168](https://www.chromestatus.com/feature/4931497563783168) and [5715811364765696](https://www.chromestatus.com/feature/5715811364765696) on Chrome Status, as reported in https://github.com/w3c/web-roadmaps/pull/58#pullrequestreview-61639401

**Comment by xfq** [comment]
Another example is Device Memory, which exists as [5119701235531776](https://www.chromestatus.com/feature/5119701235531776) and [5741299856572416](https://www.chromestatus.com/feature/5741299856572416) on Chrome Platform Status.

**Comment by tidoust** [comment]
Some more thoughts on this:

We have two levels to deal with:
- specification
- feature in a specification

We could add a third level which is the version of the spec (e.g. "CSS Fonts Level 3" or "CSS Fonts Level 4"), but I believe we can continue to consider different versions as different specifications and handle that manually in separate files.

When we have implementation info, the following cases can happen:
1. We want to talk about a specification, and implementation info is at the specification level
2. We want to talk about a feature, and implementation info as the feature level
3. We want to talk about a specification, but implementation info is at the feature level
4. We want to talk about a feature, but implementation info as the specification level

Cases can mix: we may have implementation info at the specification level and at the feature level.

Also, we may have implementation info for all the features in a spec, or not. For instance, we're only going to have implementation info for a few HTML5 features, but may have implementation info for all features in the Streams API (and thus we can reasonably assert that a user agent that supports these features implements the whole specification).

Features may not always map to implementation info that we may gather but there's not much we can do there.

Draft proposal would be to combine spec and feature levels into one JSON file:

```json
{
  "TR": "https://www.w3.org/TR/css-backgrounds-3/",
  "impl": { ... },
  "features": {
    "border-radius": {
      "url": "#the-border-radius",
      "title": "Rounded corners",
      "impl": { ... }
    },
    "background": {
      "url": "#the-background",
      "title": "Backgrounds",
      "impl": { ... }
    }
  },
  "featuresCoverSpec": false
}
```

Roadmaps could then target the spec the usual way, and target features via some naming convention such as `specname/feature`. The framework could then have some extra logic regarding implementation to say things like: "some features implemented in Safari, but maybe not the whole spec", "spec is implemented in Firefox so feature should be as well", etc.

**Comment by tidoust** [comment]
Mechanism now implementation (although note the suggested `featuresCoverSpec` property above is actually called `featuresCoverage` in practice, and is not a boolean). Closing the issue as a result. I created a follow-up issue to track data updates (#271).
