### ISSUE TITLE
HTML Media Capture

### ISSUE THREAD

**Issue by anssiko** [w3c/web-roadmaps#86]
Consider adding https://www.w3.org/TR/html-media-capture/ to http://w3c.github.io/web-roadmaps/media/capture.html

Spec status: W3C Candidate Recommendation 31 August 2017
Implementation status: shipped in Safari on iOS and Chrome for Android

cc @tidoust

**Comment by tidoust** [comment]
Indeed missing, thanks for the report! Could you have a quick look at #89?

**Comment by anssiko** [comment]
LGTM.
