### ISSUE TITLE
Implementation status of Safari and WebKit conflicts with each other

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#87]
As the title says, the implementation data of Safari and WebKit conflicts with each other sometimes.

Reported by `@kennethrohde` on Twitter originally: https://twitter.com/kennethrohde/status/913732653572083712

**Comment by tidoust** [comment]
Closed via PR #109. Information from Webkit status platform is considered accurate and used to "limit" the implementation status in Safari reported by other status platforms.

Typically, the Webkit status platform currently reports that the Web Audio API is "in development", whereas Can I use says "shipped" (well, it also says "behind a flag" but we don't currently process that info). Our system now reports "in development" for Safari for the Web Audio API as a result (and it no longer reports anything about "webkit" in this case not to confuse people)
